---
- name: Prepare timestamp + task id
  delegate_to: localhost
  run_once: true
  become: false
  ansible.builtin.set_fact:
    report_ts: "{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"
    semaphore_task_id: "{{ semaphore_vars.task_details.id | default('unknown') | string }}"

- name: Ensure reports directory exists
  delegate_to: localhost
  run_once: true
  become: false
  ansible.builtin.file:
    path: "reports"
    state: directory
    mode: "0755"

- name: Login via cookie and export Semaphore UI log
  delegate_to: localhost
  run_once: true
  become: false
  no_log: false   # wenn alles läuft → true setzen
  ansible.builtin.shell: |
    set -euo pipefail

    BASE="{{ semaphore_base_url | default('http://localhost:3000') }}"
    PROJECT_ID="{{ semaphore_project_id | default('4') }}"
    TASK_ID="{{ semaphore_task_id }}"
    TS="{{ report_ts }}"
    PB="{{ playbook_name_for_report | default('playbook') | regex_replace('[^A-Za-z0-9._-]', '_') }}"

    USER="{{ semaphore_user | default('testadmin') }}"
    PASS="{{ semaphore_pass | default('') }}"

    if [ -z "$PASS" ]; then
      echo "ERROR: semaphore_pass fehlt."
      exit 2
    fi

    # === 1) Cookie-Datei erzeugen ===
    COOKIE_FILE="cookies.txt"

    curl -s -c "$COOKIE_FILE" -X POST \
      -H "Content-Type: application/json" \
      -d "{\"auth\":\"$USER\",\"password\":\"$PASS\"}" \
      "$BASE/api/auth/login" > /dev/null

    if [ ! -f "$COOKIE_FILE" ]; then
      echo "ERROR: Cookie file not created"
      exit 3
    fi

    # === 2) Task-Meta abrufen ===
    META="$(curl -s -b "$COOKIE_FILE" \
      "$BASE/api/project/$PROJECT_ID/tasks/$TASK_ID")"

    # === 3) UI-Output abrufen ===
    OUT="$(curl -s -b "$COOKIE_FILE" \
      "$BASE/api/project/$PROJECT_ID/tasks/$TASK_ID/output")"

    # === 4) Meta-Felder extrahieren ===
    STATUS="$(python3 -c 'import json,sys; d=json.loads(sys.argv[1]); print(d.get("status",""))' "$META")"
    AUTHOR="$(python3 -c 'import json,sys; d=json.loads(sys.argv[1]); print(d.get("username",""))' "$META")"
    STARTED="$(python3 -c 'import json,sys; d=json.loads(sys.argv[1]); print(d.get("start",""))' "$META")"
    DURATION="$(python3 -c 'import json,sys; d=json.loads(sys.argv[1]); print(d.get("duration",""))' "$META")"

    OUTFILE="reports/${TS}_task${TASK_ID}_${PB}_semaphore_ui.txt"

    {
      echo "${PB} > Task #${TASK_ID}"
      echo "Status: ${STATUS}"
      echo "Author: ${AUTHOR}"
      echo "Started: ${STARTED}"
      echo "Duration: ${DURATION}"
      echo ""
      echo "$OUT"
      echo ""
    } > "$OUTFILE"

    echo "Wrote: $OUTFILE"
  args:
    executable: /bin/bash
