---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Run export script for this Semaphore task
      ansible.builtin.shell: |
        set -e
        bash tools/export_tasklog.sh "{{ semaphore_vars.task_details.id }}"
